import type { Member } from "~/types";

export const members: Member[] = [
  {
    id: "1",
    name: "Pak Budi Wijaya, S.Kom",
    role: "Pembina Divisi",
    batch: "Mentor",
    bio: "Guru produktif TKJ sekaligus pembina divisi Web Design. Passionate tentang web development dan mentoring siswa.",
    skills: ["Web Development", "Mentoring", "Project Management"],
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
    type: "core",
  },
  {
    id: "2",
    name: "Ahmad Rizki",
    role: "Ketua Divisi",
    batch: "2023",
    bio: "Memimpin divisi sejak 2024. Fokus pada React dan UI/UX design. Juara lomba web design tingkat provinsi.",
    skills: ["React", "Figma", "Leadership"],
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
    type: "core",
    social: { github: "#", instagram: "#" },
  },
  {
    id: "3",
    name: "Siti Nurhaliza",
    role: "Wakil Ketua & Design Lead",
    batch: "2023",
    bio: "Ahli UI/UX dan design system. Mengelola identitas visual divisi dan mentoring desain untuk anggota baru.",
    skills: ["UI/UX", "Figma", "Design System"],
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
    type: "core",
    social: { instagram: "#", linkedin: "#" },
  },
  {
    id: "4",
    name: "Fajar Nugroho",
    role: "Tech Lead",
    batch: "2023",
    bio: "Frontend developer dengan spesialisasi React dan TypeScript. Memimpin workshop internal divisi.",
    skills: ["React", "TypeScript", "GSAP"],
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
    type: "core",
    social: { github: "#" },
  },
  {
    id: "5",
    name: "Dina Permata",
    role: "Anggota Aktif",
    batch: "2024",
    bio: "Passionate tentang web animation dan creative coding. Aktif di proyek sekolah dan kompetisi.",
    skills: ["CSS Animation", "JavaScript", "Illustrator"],
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
    type: "active",
    social: { instagram: "#" },
  },
  {
    id: "6",
    name: "Budi Santoso",
    role: "Anggota Aktif",
    batch: "2024",
    bio: "Fokus pada responsive design dan accessibility. Sering membantu anggota baru memahami HTML/CSS.",
    skills: ["HTML", "CSS", "Accessibility"],
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&q=80",
    type: "active",
    social: { github: "#" },
  },
  {
    id: "7",
    name: "Arya Kusuma",
    role: "Anggota Aktif",
    batch: "2025",
    bio: "Anggota baru dengan semangat tinggi. Sedang belajar React dan Tailwind CSS.",
    skills: ["HTML", "CSS", "Tailwind"],
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a567c?w=200&q=80",
    type: "active",
  },
  {
    id: "8",
    name: "Rizki Pratama",
    role: "Alumni — Full Stack Dev",
    batch: "2022",
    bio: "Alumni divisi, sekarang bekerja sebagai junior web developer di startup Cirebon.",
    skills: ["React", "Node.js", "PostgreSQL"],
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&q=80",
    type: "alumni",
    social: { github: "#", linkedin: "#" },
  },
  {
    id: "9",
    name: "Maya Sari",
    role: "Alumni — UI Designer",
    batch: "2021",
    bio: "Alumni yang melanjutkan ke D3 Desain Komunikasi Visual. Freelance UI designer.",
    skills: ["UI Design", "Figma", "Branding"],
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80",
    type: "alumni",
    social: { instagram: "#", linkedin: "#" },
  },
  {
    id: "10",
    name: "Eko Prasetyo",
    role: "Alumni — Frontend Dev",
    batch: "2020",
    bio: "Salah satu alumni pertama divisi. Sekarang frontend developer di perusahaan e-commerce Jakarta.",
    skills: ["React", "Vue", "TypeScript"],
    avatar: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=200&q=80",
    type: "alumni",
    social: { github: "#", linkedin: "#" },
  },
];

export function getMembersByType(type: Member["type"]) {
  return members.filter((m) => m.type === type);
}
